### ISSUE TITLE
Support for DBAL version ^3

### ISSUE THREAD

**Issue by MarkDaleman** [metaclass-nl/filter-bundle#19]
Since there's support for Symfony 7, will there be support for DBAL ^3?

**Comment by metaclass-nl** [comment]
Ther is no dependency on DBAL in composer.json. Howerver, there is one on 
`"doctrine/orm": "^2.7"`
, i assume it does not allow DBAL ^3. But doctrine/orm 3.2 is available, and it requires
`"doctrine/dbal": "^3.8.2 || ^4",`

So the filter-bundle needs to be tested with:
`"doctrine/orm": "^3.0"`.

**Comment by metaclass-nl** [comment]
With doctrine/orm 3.2.0 the following errors occur:

TypeError: Doctrine\ORM\QueryBuilder::add(): Argument #2 ($dqlPart) must be of type object|array|string, null given, called in /var/www/html/bundles/filter-bundle/src/Filter/DateFilter.php on line 55

TypeError: Doctrine\ORM\QueryBuilder::add(): Argument #2 ($dqlPart) must be of type object|array|string, null given, called in /var/www/html/bundles/filter-bundle/src/Filter/FilterLogic.php on line 145

Obviously caused by passing null to $queryBuilder->add. Need to figure out what the old version did if null was passed and how to get the same result with the new verson. 

I have little time right now so this may take a while (up to a month).

**Comment by MarkDaleman** [comment]
Hello @metaclass-nl,

My colleague found the following:

![afbeelding](https://github.com/metaclass-nl/filter-bundle/assets/2061273/895c2943-aa77-4244-988f-7baaebbbcf65)

If the `$oldWhere` is null, you could reset the DQL part.

This seems to work!

**Comment by metaclass-nl** [comment]
Thanks a lot! With this all tests run with doctrine/orm 3.2.0. 

Published release [v3.2.0](https://github.com/metaclass-nl/filter-bundle/releases/tag/v3.2.0)
